/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Controladores.CentrosDeCostosControl;
import Controladores.EmpresaControl;
import proyectosjava.VariablesGlobales;



/**
 *
 * @author ivanruiz
 */
public class CentrosDeCostos extends javax.swing.JInternalFrame {
    
    
     private CentrosDeCostosControl CencCont = new CentrosDeCostosControl();
     private EmpresaControl EmpCont = new EmpresaControl();

    public Integer Id = 0;
    public String Codigo = "";
    public String Nombre = "";
    public String Empresa_id = "";
    
   public Object[][] DatosCentrosDeCostos;
   public Object[][] DatosEmpresa;
    
     
    public Integer TotalRegistros=0;
    public Integer Siguiente=0;
    public Integer Anterior=0;
    public Integer Registros=0;

    /**
     * Creates new form CentrosDeCostos
     */
    public CentrosDeCostos() {
        initComponents();
        
         Object[][] DatosEmpresas = EmpCont.BuscarEmpresa("", "", "", "", "", "", "", "", Integer.toString(0));
        jtextempresa_id.removeAllItems();
        for(int i=0;i<DatosEmpresas.length;i++){
            String Item = (String)DatosEmpresas[i][8] +"-"+  (String)DatosEmpresas[i][0];
          
           jtextempresa_id.addItem(Item);
        }
    }

    
    public void ObtenerDatos(){
       Id = 0;
       Nombre = jtextnombre.getText();
       Codigo = jtextcodigo.getText() ;
       
       String Item="";
        Item = (String)jtextempresa_id.getSelectedItem();
        //Index =  (Int)jtextempresa_id.getSelectedIndex()
       if (Item!=null){
           Empresa_id = Item.substring(0,  Item.indexOf("-"));
           System.out.println(Item.substring(0,  Item.indexOf("-")));
       }
       
      
    }
    
    public void EventoNuevo() {
        jtextnombre.setText("");
        jtextcodigo.setText("");
    }

    public void EventoGrabar() {
        ObtenerDatos();

        if (CencCont.Existe_CentroDeCosto(Id, Nombre, Codigo, Empresa_id)) {
            CencCont.ActualizarCentroDeCosto(Nombre, Codigo, Empresa_id, Integer.toString(CencCont.Id));
        } else {
            CencCont.CrearCentroDeCosto(Nombre, Codigo, Empresa_id);
        }

    }

    public void EventoEliminar() {

    }

    public void EventoImprimir() {

    }

    public void EventoSiguiente() {
        
        
         
             jtextnombre.setText(DatosCentrosDeCostos[Registros][0].toString());
            jtextcodigo.setText(DatosCentrosDeCostos[Registros][1].toString());
             DatosEmpresa = EmpCont.getDatoEmpresa(DatosCentrosDeCostos[Registros][2].toString());
            jtextempresa_id.setSelectedItem(DatosCentrosDeCostos[Registros][2].toString() +"-"+DatosEmpresa[0][0]);
            //jtextempresa_id.setText(DatosCentrosDeCostos[Registros][2].toString());
            
           Registros = Registros + 1;
           if (Registros>TotalRegistros ){Registros = TotalRegistros  ;}
           System.out.println("Siguiente" + Registros + "Total" + TotalRegistros);
           

           
           
    }

    public void EventoAnterior() {
        
        

           jtextnombre.setText(DatosCentrosDeCostos[Registros][0].toString());
            jtextcodigo.setText(DatosCentrosDeCostos[Registros][1].toString());
            DatosEmpresa = EmpCont.getDatoEmpresa(DatosCentrosDeCostos[Registros][2].toString());
            jtextempresa_id.setSelectedItem(DatosCentrosDeCostos[Registros][2].toString() +"-"+DatosEmpresa[0][0]);
            
            Registros =Registros  - 1;
            if (Registros<0 ){Registros = 0;}
            
             System.out.println("Anterior" + Registros + "Total" + TotalRegistros);
           
    }

    public void EventoBuscar() {
            ObtenerDatos();
             DatosCentrosDeCostos = CencCont.BuscarCentroDeCosto(Nombre, Codigo, Empresa_id, Integer.toString(Id));
                      TotalRegistros = DatosCentrosDeCostos.length - 1   ;
             if (TotalRegistros - 1 < 0 ){TotalRegistros=0;}
             System.out.println("Buscar-----" + TotalRegistros);
             
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtextcodigo = new javax.swing.JTextField();
        jtextnombre = new javax.swing.JTextField();
        jtextempresa_id = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Centros de Costos");

        jLabel1.setText("Codigo:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Empresa:");

        jtextcodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtextcodigoFocusLost(evt);
            }
        });
        jtextcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextcodigoActionPerformed(evt);
            }
        });

        jtextempresa_id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jtextempresa_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtextempresa_idItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextempresa_id, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextempresa_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextcodigoActionPerformed

    private void jtextcodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtextcodigoFocusLost
        // TODO add your handling code here:
        
        ObtenerDatos();

        if (CencCont.Existe_CentroDeCosto(Id, Nombre, Codigo, Empresa_id)) {
            DatosCentrosDeCostos = CencCont.getDatoCentroDeCosto(CencCont.Id);
            
            jtextnombre.setText(DatosCentrosDeCostos[0][0].toString());
            jtextcodigo.setText(DatosCentrosDeCostos[0][1].toString());
             DatosEmpresa = EmpCont.getDatoEmpresa(DatosCentrosDeCostos[0][2].toString());
            jtextempresa_id.setSelectedItem(DatosCentrosDeCostos[0][2].toString()+"-"+DatosEmpresa[0][0]);

        }
    }//GEN-LAST:event_jtextcodigoFocusLost

    private void jtextempresa_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtextempresa_idItemStateChanged
        // TODO add your handling code here:
        String Item="";
        Item = (String)jtextempresa_id.getSelectedItem();
        //Index =  (Int)jtextempresa_id.getSelectedIndex()
       if (Item!=null){
           Empresa_id = Item.substring(0,  Item.indexOf("-"));
           System.out.println(Item.substring(0,  Item.indexOf("-")));
       }
        
        
        
        
    }//GEN-LAST:event_jtextempresa_idItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtextcodigo;
    private javax.swing.JComboBox jtextempresa_id;
    private javax.swing.JTextField jtextnombre;
    // End of variables declaration//GEN-END:variables
}
