/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Controladores.EmpresaControl;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author ivanruiz
 */
public class Empresa extends javax.swing.JInternalFrame {

    private EmpresaControl EmpCont = new EmpresaControl();

    public Integer Id = 0;
    public String Nombre = "";
    public String Ruc = "";
    public String Telefono = "";
    public String Fax = "";
    public String Correo = "";
    public String Direccion = "";
    public String Web = "";
    public String Personas_id = "";
   public Object[][] DatosEmpresa;
    
     
    public Integer TotalRegistros=0;
    public Integer Siguiente=0;
    public Integer Anterior=0;
    public Integer Registros=0;

    /**
     * Creates new form Empresa
     */
    public Empresa() {
        initComponents();
    }

    public void ObtenerDatos(){
       Id = 0;
       Nombre = jtextnombre.getText();
       Ruc = jtextruc.getText() ;
       Telefono = jtexttelefono.getText();
       Fax = jtextfax.getText();
       Correo =jtextcorreo.getText();
       Direccion = jtextdireccion.getText() ;
       Web = jtextweb.getText();
       Personas_id = jtextpersonas_id.getText();
      
    }
    
    public void EventoNuevo() {
        jtextnombre.setText("");
        jtextruc.setText("");
        jtexttelefono.setText("");
        jtextfax.setText("");
        jtextcorreo.setText("");
        jtextdireccion.setText("");
        jtextweb.setText("");
        jtextpersonas_id.setText("");
    }

    public void EventoGrabar() {
        ObtenerDatos();

        if (EmpCont.Existe_Empresa(Id, Nombre, Ruc, Telefono, Fax, Correo, Direccion, Web, Personas_id)) {
            EmpCont.ActualizarEmpresa(Nombre, Ruc, Telefono, Fax, Correo, Direccion, Web, Personas_id, Integer.toString(EmpCont.Id));
        } else {
            EmpCont.CrearEmpresa(Nombre, Ruc, Telefono, Fax, Correo, Direccion, Web, Personas_id);
        }

    }

    public void EventoEliminar() {

    }

    public void EventoImprimir() {

    }

    public void EventoSiguiente() {
        
        
         
            jtextnombre.setText(DatosEmpresa[Registros][0].toString());
            jtextruc.setText(DatosEmpresa[Registros][1].toString());
            jtexttelefono.setText(DatosEmpresa[Registros][2].toString());
            jtextfax.setText(DatosEmpresa[Registros][3].toString());
            jtextcorreo.setText(DatosEmpresa[Registros][4].toString());
            jtextdireccion.setText(DatosEmpresa[Registros][5].toString());
            jtextweb.setText(DatosEmpresa[Registros][6].toString());
            jtextpersonas_id.setText(DatosEmpresa[Registros][7].toString());
            
           Registros = Registros + 1;
           if (Registros>TotalRegistros ){Registros = TotalRegistros  ;}
           

           
           
    }

    public void EventoAnterior() {
        
        

           jtextnombre.setText(DatosEmpresa[Registros][0].toString());
            jtextruc.setText(DatosEmpresa[Registros][1].toString());
            jtexttelefono.setText(DatosEmpresa[Registros][2].toString());
            jtextfax.setText(DatosEmpresa[Registros][3].toString());
            jtextcorreo.setText(DatosEmpresa[Registros][4].toString());
            jtextdireccion.setText(DatosEmpresa[Registros][5].toString());
            jtextweb.setText(DatosEmpresa[Registros][6].toString());
            jtextpersonas_id.setText(DatosEmpresa[Registros][7].toString());
            Registros =Registros  - 1;
            if (Registros<0 ){Registros = 0;}
    }

    public void EventoBuscar() {
            ObtenerDatos();
             DatosEmpresa = EmpCont.BuscarEmpresa(Nombre, Ruc, Telefono, Fax, Correo, Direccion, Web, Personas_id, Integer.toString(Id));
             TotalRegistros = DatosEmpresa.length  -1  ;
             if (TotalRegistros - 1 < 0 ){TotalRegistros=0;}
             System.out.println("Buscar-----" + TotalRegistros);
             
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtextruc = new javax.swing.JTextField();
        jtextnombre = new javax.swing.JTextField();
        jtexttelefono = new javax.swing.JTextField();
        jtextfax = new javax.swing.JTextField();
        jtextcorreo = new javax.swing.JTextField();
        jtextdireccion = new javax.swing.JTextField();
        jtextweb = new javax.swing.JTextField();
        jtextpersonas_id = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Empresas");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Nombre:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("R.U.C:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Telefono:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Fax:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("Correo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel6.setText("Direccion:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel7.setText("Web:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("Responsable:");

        jtextruc.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtextruc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtextrucFocusLost(evt);
            }
        });
        jtextruc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtextrucKeyTyped(evt);
            }
        });

        jtextnombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtextnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextnombreActionPerformed(evt);
            }
        });

        jtexttelefono.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jtextfax.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jtextcorreo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jtextdireccion.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jtextweb.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jtextpersonas_id.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtextruc)
                    .addComponent(jtextnombre)
                    .addComponent(jtextfax)
                    .addComponent(jtextcorreo)
                    .addComponent(jtextdireccion)
                    .addComponent(jtextweb)
                    .addComponent(jtextpersonas_id, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(jtexttelefono))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextruc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtexttelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextweb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtextpersonas_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextrucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtextrucKeyTyped
        // TODO add your handling code here:
       //ObtenerDatos();
       
        char caracter = evt.getKeyChar();
        if (((caracter < '0') || (caracter > '9')) && (caracter != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }else
        {
 
        }
    }//GEN-LAST:event_jtextrucKeyTyped

    private void jtextnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextnombreActionPerformed

    private void jtextrucFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtextrucFocusLost
        // TODO add your handling code here:
        ObtenerDatos();

        if (EmpCont.Existe_Empresa(Id, Nombre, Ruc, Telefono, Fax, Correo, Direccion, Web, Personas_id)) {
            DatosEmpresa = EmpCont.getDatoEmpresa(EmpCont.Id);
            jtextnombre.setText(DatosEmpresa[0][0].toString());
            jtextruc.setText(DatosEmpresa[0][1].toString());
            jtexttelefono.setText(DatosEmpresa[0][2].toString());
            jtextfax.setText(DatosEmpresa[0][3].toString());
            jtextcorreo.setText(DatosEmpresa[0][4].toString());
            jtextdireccion.setText(DatosEmpresa[0][5].toString());
            jtextweb.setText(DatosEmpresa[0][6].toString());
            jtextpersonas_id.setText(DatosEmpresa[0][7].toString());

        }

    }//GEN-LAST:event_jtextrucFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jtextcorreo;
    private javax.swing.JTextField jtextdireccion;
    private javax.swing.JTextField jtextfax;
    private javax.swing.JTextField jtextnombre;
    private javax.swing.JTextField jtextpersonas_id;
    private javax.swing.JTextField jtextruc;
    private javax.swing.JTextField jtexttelefono;
    private javax.swing.JTextField jtextweb;
    // End of variables declaration//GEN-END:variables
}
