/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Controladores.CentrosDeCostosControl;
import Controladores.EmpresaControl;
import javax.swing.JOptionPane;
import proyectosjava.VariablesGlobales;



/**
 *
 * @author ivanruiz
 */
public class SelecionarEmpresa extends javax.swing.JInternalFrame {
    
     private CentrosDeCostosControl CencCont = new CentrosDeCostosControl();
     private EmpresaControl EmpCont = new EmpresaControl();

    public Integer Id = 0;
    public String Codigo = "";
    public String Nombre = "";
    public String Empresa_id = "";
    
   public Object[][] DatosCentrosDeCostos;
   public Object[][] DatosEmpresa;
    
     
    public Integer TotalRegistros=0;
    public Integer Siguiente=0;
    public Integer Anterior=0;
    public Integer Registros=0;


    /**
     * Creates new form SelecionarEmpresa
     */
    public SelecionarEmpresa() {
        initComponents();
        Object[][] DatosEmpresas = EmpCont.BuscarEmpresa("", "", "", "", "", "", "", "", Integer.toString(0));
        jtextempresa_id.removeAllItems();
        for(int i=0;i<DatosEmpresas.length;i++){
            String Item = (String)DatosEmpresas[i][8] +"-"+  (String)DatosEmpresas[i][0];
           jtextempresa_id.addItem(Item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtextempresa_id = new javax.swing.JComboBox();

        setClosable(true);
        setTitle("Selecionar Empresa");

        jLabel1.setText("Empresa:");

        jtextempresa_id.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jtextempresa_id.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jtextempresa_idItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtextempresa_id, 0, 273, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtextempresa_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextempresa_idItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jtextempresa_idItemStateChanged
        // TODO add your handling code here:
        
        String Item="";
        Item = (String)jtextempresa_id.getSelectedItem();
        //Index =  (Int)jtextempresa_id.getSelectedIndex()
       if (Item!=null){
           Empresa_id = Item.substring(0,  Item.indexOf("-"));
           
           
           int respuesta = JOptionPane.showConfirmDialog(null, "Cambio de empresa", "¿Desea cambiar de empresa?", JOptionPane.YES_NO_CANCEL_OPTION);
           switch (respuesta) {
               case JOptionPane.YES_OPTION:
//Operaciones en caso afirmativo
                   VariablesGlobales.setVar(Empresa_id);
                   break;
               case JOptionPane.NO_OPTION:
//Operaciones en caso negativo
                   break;
               case JOptionPane.CANCEL_OPTION:
//Operaciones en caso de cancelar
                   break;
           }
           
           
           
           
           
           
           //System.out.println(Item.substring(0,  Item.indexOf("-")) + VariablesGlobales.EmpresaSelecionada);
       }
    }//GEN-LAST:event_jtextempresa_idItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox jtextempresa_id;
    // End of variables declaration//GEN-END:variables
}
