/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vistas;

import Controladores.EmpresaControl;
import Controladores.TiposDeRetencionesControl;

/**
 *
 * @author USER
 */
public class TiposDeRetenciones extends javax.swing.JInternalFrame {
    
       private TiposDeRetencionesControl TipCont = new TiposDeRetencionesControl();
     private EmpresaControl EmpCont = new EmpresaControl();

    
    public Object[][] DatosTiposDeRetenciones;
    public Integer Id = 0;
    public String Codigo = "";
    public String Nombre = "";
    public Double Porcentaje = 0.00;
    
    public Integer TotalRegistros=0;
    public Integer Siguiente=0;
    public Integer Anterior=0;
    public Integer Registros=0;


    /**
     * Creates new form TiposDeRetenciones
     */
    public TiposDeRetenciones() {
        initComponents();
    }

     public void ObtenerDatos(){
       Id = 0;
       Nombre = jtextnombre.getText();
       Codigo = jtextcodigo.getText() ;
       Porcentaje= Double.parseDouble(jtextporcentaje.getText()) ;
       
        System.out.println(Porcentaje);
    }
    
    
     public void EventoNuevo() {
        jtextnombre.setText("");
        jtextcodigo.setText("");
        jtextporcentaje.setText("0.00");
    }

    public void EventoGrabar() {
        ObtenerDatos();

        if (TipCont.Existe_TiposDeRetenciones(Id, Codigo, Nombre, Porcentaje)){
            TipCont.ActualizarTiposDeRetencion(Codigo, Nombre, Porcentaje, Integer.toString(TipCont.Id));
                    
        } else {
            TipCont.CrearTiposDeRetenciones(Codigo, Nombre, Porcentaje);
        }

    }
     
    
    public void EventoEliminar() {

    }

    public void EventoImprimir() {

    }

    public void EventoSiguiente() {
        
        
             jtextcodigo.setText(DatosTiposDeRetenciones[Registros][0].toString());
             jtextnombre.setText(DatosTiposDeRetenciones[Registros][1].toString());
             jtextporcentaje.setText(DatosTiposDeRetenciones[Registros][2].toString());
           
           Registros = Registros + 1;
           if (Registros>TotalRegistros ){Registros = TotalRegistros  ;}
           System.out.println("Siguiente" + Registros + "Total" + TotalRegistros);
           

           
           
    }

    public void EventoAnterior() {
        
        

            jtextcodigo.setText(DatosTiposDeRetenciones[Registros][0].toString());
             jtextnombre.setText(DatosTiposDeRetenciones[Registros][1].toString());
             jtextporcentaje.setText(DatosTiposDeRetenciones[Registros][2].toString());
           
            Registros =Registros  - 1;
            if (Registros<0 ){Registros = 0;}
            
             System.out.println("Anterior" + Registros + "Total" + TotalRegistros);
           
    }

    public void EventoBuscar() {
            ObtenerDatos();
             DatosTiposDeRetenciones = TipCont.BuscarTiposDeRetenciones(Codigo, Nombre, Porcentaje, Integer.toString(Id));
                      TotalRegistros = DatosTiposDeRetenciones.length - 1   ;
             if (TotalRegistros - 1 < 0 ){TotalRegistros=0;}
             System.out.println("Buscar-----" + TotalRegistros);
             
    }

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtextcodigo = new javax.swing.JTextField();
        jtextnombre = new javax.swing.JTextField();
        jtextporcentaje = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Tipos de Retenciones");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Codigo:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setText("Nombre:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Porcentaje:");

        jtextcodigo.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtextcodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtextcodigoFocusLost(evt);
            }
        });
        jtextcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextcodigoActionPerformed(evt);
            }
        });

        jtextnombre.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtextnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextnombreActionPerformed(evt);
            }
        });

        jtextporcentaje.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        jtextporcentaje.setText("0.00");
        jtextporcentaje.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jtextporcentaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextporcentajeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtextcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtextporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtextcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtextnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtextporcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextnombreActionPerformed

    private void jtextporcentajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextporcentajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextporcentajeActionPerformed

    private void jtextcodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtextcodigoFocusLost
 ObtenerDatos();

        if (TipCont.Existe_TiposDeRetenciones(Id, Codigo, Nombre, Porcentaje)) {
            DatosTiposDeRetenciones = TipCont.getDatoTiposDeRetenciones(TipCont.Id);
            jtextcodigo.setText(DatosTiposDeRetenciones[0][0].toString());
            jtextnombre.setText(DatosTiposDeRetenciones[0][1].toString());
            jtextporcentaje.setText(DatosTiposDeRetenciones[0][2].toString());
            
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextcodigoFocusLost

    private void jtextcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextcodigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtextcodigo;
    private javax.swing.JTextField jtextnombre;
    private javax.swing.JFormattedTextField jtextporcentaje;
    // End of variables declaration//GEN-END:variables
}
