/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectosjava;

import BaseDatos.Sql;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author ivanruiz
 */
public class Interfaz extends javax.swing.JFrame {
    
    private Sql mySql = new Sql();
    
   

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
        
        
         //se crea la raiz
         DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Sistema - Francisco Ruiz");
         DefaultMutableTreeNode empresa;
         DefaultMutableTreeNode modulo;
         DefaultMutableTreeNode submodulo;
         DefaultMutableTreeNode opcion;
         
          String[] columnas_empr={"id","nombre","ruc","correo"};
          Object[][] data_empr = mySql.GetTabla(columnas_empr, "empresas", "select * from empresas;"); 
          if( data_empr.length > 0)
              {
                  for (int i = 0; i < data_empr.length; i++) {
                        empresa = new DefaultMutableTreeNode(data_empr[i][1]);
                        raiz.add(empresa);
                        
                        String[] columnas_modu={"id","nombre"};
                        Object[][] data_modu = mySql.GetTabla(columnas_modu, "modulos", "select * from modulos;"); 
                        if( data_modu.length > 0)
                           {    
                               for (int j = 0; j < data_modu.length; j++) {
                                    modulo = new DefaultMutableTreeNode(data_modu[j][1]);
                                    empresa.add(modulo);
                                    
                                    String[] columnas_subm={"id","nombre"};
                                    Object[][] data_subm = mySql.GetTabla(columnas_subm, "submodulos", "select * from submodulos where modulos_id="+data_modu[j][0]+";"); 
              
                                     if( data_subm.length > 0)
                                        {
                                            for (int k = 0; k < data_subm.length; k++) {
                                                submodulo = new DefaultMutableTreeNode(data_subm[k][1]);
                                                modulo.add(submodulo);
                                                
                                                String[] columnas_opci={"id","nombre"};
                                                Object[][] data_opci = mySql.GetTabla(columnas_subm, "opciones", "select * from opciones where submodulo_modulos_id="+data_modu[j][0]+" and  submodulo_id="+data_subm[k][0]+";"); 
              
                                                 if( data_opci.length > 0)
                                                    {
                                                        for (int l = 0; l < data_opci.length; l++) {
                                                            opcion = new DefaultMutableTreeNode(data_opci[l][1]);
                                                            submodulo.add(opcion);
                                                        }
                                                    }
                                                
                                                
                                            }
                                        }
                                    
                                    
                                   
                
                               }
      
                            }                  
                        
                        
                      
            
                  }
              }
          
        
          //se crea hojas departamentos
            
            
              
            
            DefaultTreeModel modelo = new DefaultTreeModel(raiz);
            this.jTree1.setModel(modelo);

            

     
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables
}
